"""CLI for a privacy-first Instagram friendship graph."""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
import zipfile
from collections import defaultdict, deque
from pathlib import Path, PurePosixPath

USERNAME = re.compile(r"[A-Za-z0-9._]{1,30}\Z")
FOLLOWERS_FILE = re.compile(r"followers(?:_\d+)?\.json\Z")
MARKER = "<!-- Generated by instagram-friendship-graph. Edit your own notes elsewhere. -->"
MAX_JSON_BYTES = 25_000_000
COLORS = {0: "1", 1: "4", 2: "5", 3: "6"}


class InputError(ValueError):
    """An input file is missing or malformed."""


def username(value: object) -> str:
    if not isinstance(value, str) or not USERNAME.fullmatch(value):
        raise InputError(f"Invalid Instagram username: {value!r}")
    return value.lower()


def names_from_meta(value: object, label: str) -> set[str]:
    if isinstance(value, dict):
        value = value.get("relationships_following")
    if not isinstance(value, list):
        raise InputError(f"{label}: expected a list of Instagram relationships")
    names: set[str] = set()
    for index, row in enumerate(value):
        if not isinstance(row, dict):
            raise InputError(f"{label}: relationship {index} is not an object")
        data = row.get("string_list_data")
        if not isinstance(data, list) or not data or not isinstance(data[0], dict):
            raise InputError(f"{label}: relationship {index} has no string_list_data")
        names.add(username(data[0].get("value")))
    return names


def _is_connection_file(name: str) -> bool:
    return "followers_and_following" in PurePosixPath(name).parts


def load_export(path: Path) -> tuple[set[str], set[str]]:
    """Read only followers/following JSON from a Meta export directory or ZIP."""
    entries: list[tuple[str, bytes]] = []
    if path.is_dir():
        for item in path.rglob("*.json"):
            relative = item.relative_to(path).as_posix()
            if (_is_connection_file(relative) or path.name == "followers_and_following") and (FOLLOWERS_FILE.fullmatch(item.name) or item.name == "following.json"):
                if item.stat().st_size > MAX_JSON_BYTES:
                    raise InputError(f"Export JSON is too large: {relative}")
                entries.append((relative, item.read_bytes()))
    elif path.is_file() and zipfile.is_zipfile(path):
        with zipfile.ZipFile(path) as archive:
            for item in archive.infolist():
                name = PurePosixPath(item.filename)
                if _is_connection_file(item.filename) and (FOLLOWERS_FILE.fullmatch(name.name) or name.name == "following.json"):
                    if item.file_size > MAX_JSON_BYTES:
                        raise InputError(f"Export JSON is too large: {item.filename}")
                    entries.append((item.filename, archive.read(item)))
    else:
        raise InputError(f"Expected a Meta export directory or ZIP: {path}")

    followers: set[str] = set()
    following: set[str] = set()
    found_followers = found_following = False
    for name, raw in entries:
        try:
            data = json.loads(raw)
        except (ValueError, UnicodeDecodeError) as exc:
            raise InputError(f"Cannot read {name}: {exc}") from exc
        if FOLLOWERS_FILE.fullmatch(PurePosixPath(name).name):
            found_followers = True
            followers.update(names_from_meta(data, name))
        else:
            found_following = True
            following.update(names_from_meta(data, name))
    if not found_followers or not found_following:
        raise InputError("Export needs followers_1.json (or followers.json) and following.json in followers_and_following/")
    return followers, following


def load_observations(path: Path | None, root: str) -> list[tuple[str, set[str], set[str]]]:
    if path is None:
        return []
    try:
        rows = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise InputError(f"Cannot read observations {path}: {exc}") from exc
    if not isinstance(rows, list):
        raise InputError("Observations must be a JSON array")
    result = []
    seen = {root}
    for index, row in enumerate(rows):
        if not isinstance(row, dict) or set(row) != {"account", "followers", "following"}:
            raise InputError(f"Observation {index} needs exactly account, followers, following")
        account = username(row["account"])
        if account in seen:
            raise InputError(f"Duplicate observation or root account: {account}")
        seen.add(account)
        followers, following = row["followers"], row["following"]
        if not isinstance(followers, list) or not isinstance(following, list):
            raise InputError(f"Observation {index}: followers and following must be arrays")
        result.append((account, {username(x) for x in followers}, {username(x) for x in following}))
    return result


def add_snapshot(follows: set[tuple[str, str]], account: str, followers: set[str], following: set[str]) -> None:
    follows.update((other, account) for other in followers if other != account)
    follows.update((account, other) for other in following if other != account)


def mutual_graph(follows: set[tuple[str, str]]) -> dict[str, set[str]]:
    graph: dict[str, set[str]] = defaultdict(set)
    for source, target in follows:
        if (target, source) in follows:
            graph[source].add(target)
            graph[target].add(source)
    return graph


def distances(graph: dict[str, set[str]], root: str, max_depth: int = 3) -> dict[str, int]:
    result = {root: 0}
    queue = deque([root])
    while queue:
        current = queue.popleft()
        if result[current] >= max_depth:
            continue
        for neighbor in sorted(graph.get(current, ())):
            if neighbor not in result:
                result[neighbor] = result[current] + 1
                queue.append(neighbor)
    return result


def _write_generated(path: Path, content: str) -> None:
    if path.exists() and MARKER not in path.read_text(encoding="utf-8"):
        raise InputError(f"Refusing to overwrite a non-generated file: {path}")
    path.write_text(content, encoding="utf-8")


def _note(account: str, degree: int, neighbors: list[str], root: str) -> str:
    links = "\n".join(f"- [[{'Home' if x == root else 'People/' + x}|@{x}]]" for x in neighbors)
    return (
        f"---\nusername: {account}\ndegree: {degree}\ntags:\n  - degree-{degree}\n---\n"
        f"{MARKER}\n\n# @{account}\n\n"
        f"**{degree} hop{'s' if degree != 1 else ''} from @{root}.** "
        "This measures reciprocal follow links observed in the supplied data, not real-life closeness.\n\n"
        f"[Instagram profile](https://www.instagram.com/{account}/)\n\n## Observed mutual connections\n\n"
        f"{links or 'None in the three-hop view.'}\n"
    )


def _canvas(degree: dict[str, int], graph: dict[str, set[str]], root: str) -> str:
    by_degree = {d: sorted(n for n, value in degree.items() if value == d) for d in range(4)}
    radii = {0: 0}
    previous = 0
    for d in range(1, 4):
        radius = max(previous + 360, math.ceil(len(by_degree[d]) * 105 / math.pi))
        radii[d] = radius
        previous = radius
    nodes = []
    for d in range(4):
        names = by_degree[d]
        for index, name in enumerate(names):
            angle = 2 * math.pi * index / len(names) - math.pi / 2 if names else 0
            nodes.append({
                "id": name, "type": "file", "file": "Home.md" if name == root else f"People/{name}.md",
                "x": round(radii[d] * math.cos(angle) - 90),
                "y": round(radii[d] * math.sin(angle) - 45),
                "width": 180, "height": 90, "color": COLORS[d],
            })
    edges = []
    for source in sorted(degree):
        for target in sorted(graph.get(source, ())):
            if target in degree and source < target:
                edges.append({"id": f"{source}--{target}", "fromNode": source, "toNode": target, "toEnd": "none"})
    return json.dumps({"nodes": nodes, "edges": edges}, indent=2) + "\n"


def write_vault(output: Path, graph: dict[str, set[str]], degree: dict[str, int], root: str) -> None:
    people = output / "People"
    people.mkdir(parents=True, exist_ok=True)
    for name in sorted(degree):
        neighbors = sorted(n for n in graph.get(name, ()) if n in degree)
        target = output / "Home.md" if name == root else people / f"{name}.md"
        _write_generated(target, _note(name, degree[name], neighbors, root))
    for stale in people.glob("*.md"):
        if stale.stem not in degree and MARKER in stale.read_text(encoding="utf-8"):
            stale.unlink()
    canvas = output / "Friendship Rings.canvas"
    if canvas.exists():
        try:
            old = json.loads(canvas.read_text(encoding="utf-8"))
        except ValueError as exc:
            raise InputError(f"Refusing to overwrite invalid canvas: {canvas}") from exc
        if not isinstance(old, dict) or old.get("_generated_by") != "instagram-friendship-graph":
            raise InputError(f"Refusing to overwrite a non-generated canvas: {canvas}")
    content = json.loads(_canvas(degree, graph, root))
    content["_generated_by"] = "instagram-friendship-graph"
    canvas.write_text(json.dumps(content, indent=2) + "\n", encoding="utf-8")


def build(root: str, followers: set[str], following: set[str], observations: list[tuple[str, set[str], set[str]]], output: Path) -> dict[int, int]:
    follows: set[tuple[str, str]] = set()
    add_snapshot(follows, root, followers, following)
    for account, observed_followers, observed_following in observations:
        add_snapshot(follows, account, observed_followers, observed_following)
    graph = mutual_graph(follows)
    degree = distances(graph, root)
    write_vault(output, graph, degree, root)
    return {d: sum(value == d for value in degree.values()) for d in range(4)}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build a local Obsidian friendship graph from Instagram data")
    sub = parser.add_subparsers(dest="command", required=True)
    build_parser = sub.add_parser("build", help="Build from your Meta JSON export")
    build_parser.add_argument("--account", required=True, help="Your Instagram username")
    build_parser.add_argument("--export", type=Path, required=True, help="Meta export ZIP or extracted directory")
    build_parser.add_argument("--observations", type=Path, help="Optional observed account snapshots JSON")
    build_parser.add_argument("--output", type=Path, default=Path("local-data/vault"))
    demo_parser = sub.add_parser("demo", help="Build a fictional three-degree demo")
    demo_parser.add_argument("--output", type=Path, default=Path("local-data/demo-vault"))
    args = parser.parse_args(argv)
    try:
        if args.command == "demo":
            root = "you"
            followers = {"alex", "bea", "unreturned"}
            following = {"alex", "bea", "not_following_back"}
            observations = [
                ("alex", {"you", "bea", "casey"}, {"you", "bea", "casey"}),
                ("bea", {"you", "alex"}, {"you", "alex"}),
                ("casey", {"alex", "drew"}, {"alex", "drew"}),
                ("drew", {"casey"}, {"casey"}),
            ]
        else:
            root = username(args.account)
            followers, following = load_export(args.export)
            observations = load_observations(args.observations, root)
        counts = build(root, followers, following, observations, args.output)
    except (InputError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(f"Vault: {args.output.resolve()}")
    print("Nodes by degree: " + ", ".join(f"{d}: {counts[d]}" for d in range(4)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
